name: CMake Build on multiple platforms

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release, Debug]
        include:
          - os: ubuntu-latest
            triplet: x64-linux
            preset: linux
          - os: windows-latest
            triplet: x64-windows-static-md
            preset: windows

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Cache VCPKG
      uses: actions/cache@v4
      with:
        path: |
          ${{ github.workspace }}/vcpkg/installed
          ${{ github.workspace }}/vcpkg/buildtrees
          ${{ github.workspace }}/vcpkg/packages
        key: vcpkg-${{ matrix.os }}-${{ matrix.triplet }}-${{ hashFiles('**/vcpkg.json') }}
        restore-keys: |
          vcpkg-${{ matrix.os }}-${{ matrix.triplet }}-

    - name: Install Linux Dependencies (Linux Only)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt update -y
        sudo apt full-upgrade -y
        sudo apt install -y ack autoconf automake autoconf-archive make \
        build-essential gcc g++ curl wget gcc-multilib g++-multilib \
        gettext git cmake patch unzip tar libtool vim

        sudo apt install -y pkg-config pipewire libpipewire-0.3-dev

    - name: Enable MSVC Developer Command Prompt (Windows Only)
      if: ${{ matrix.os == 'windows-latest' }}
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        vsversion: 2022
   
    - name: Setup VCPKG
      uses: lukka/run-vcpkg@v11

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.8.2

    - name: Configure CMake
      env:
        VCPKG_ROOT: ${{ github.workspace }}/vcpkg
        Qt6_DIR: ${{ steps.install-qt.outputs.Qt6_DIR }}

      run: |
        cmake --preset ${{ matrix.preset }}-${{ matrix.build_type }}
        
    - name: Build
      run: |
        cmake --build --preset ${{ matrix.preset }}-${{ matrix.build_type }} --parallel

    - name: Install
      run: |
        cmake --install cmake_build/${{ matrix.preset }}-${{ matrix.build_type }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-${{ matrix.build_type }}
        path: |
          cmake_install/${{ matrix.preset }}-${{ matrix.build_type }}/*

        if-no-files-found: error

